[package]
name = "project-finder"
authors = [ "Kristofers Solo <dev@kristofers.xyz>" ]
version = "0.1.2"
edition = "2024"
description = "Fast project finder for developers"
repository = "https://github.com/kristoferssolo/project-finder"
documentation = "https://docs.rs/project-finder"
homepage = "https://github.com/kristoferssolo/project-finder"
license = "MIT OR Apache-2.0"
keywords = [ "cli", "string", "text", "utility" ]
categories = [ "command-line-utilities" ]
exclude = [
  ".github/",
  ".gitignore",
  "tests/",
  "benches/",
  "scripts/",
  "justifle",
  "*.png",
  "*.md",
]
readme = "README.md"

[dependencies]
clap = {version = "4.6", features = [ "derive" ]}
color-eyre = "0.6"
regex = "1.13"
serde = {version = "1", features = [ "derive" ]}
thiserror = "2.0"
tokio = {version = "1.53", features = [
  "io-util",
  "macros",
  "process",
  "rt",
  "rt-multi-thread",
  "sync",
]}
toml = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"
which = "8.0"

[dev-dependencies]
claims = "0.8"
criterion = "0.8"
csv = "1.4"
rstest = "0.26"
tempfile = "3.27"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false
